---
- name: Monitoring disable
  hosts: managed_nodes
  become: true

  roles:
    - role: collectd-role
      vars:
        monitoring_action: disabled        
        monitoring_modules:
          - cpu
          - df
          - processes
          - protocols
          - swap
          - tcpconns
          - uptime
          - users
          - vmem        
