---
- name: Monitoring enable
  hosts: managed_nodes
  become: true

  roles:
    - role: collectd-role
      vars:
# default monitoring_actin is install        
        monitoring_modules:
          - cpu
          - df
          - processes
          - protocols
          - swap
          - tcpconns
          - uptime
          - users
          - vmem        
