---
- name: Install mc package
  yum:
    name: mc
    state: present

- name: Install nano package
  yum:
    name: nano
    state: present

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  notify: Reboot the servers if SELinux is changed