---
- name: Mc needed
  package:
    name: mc
    state: present

- name: Nano needed
  package:
    name: nano
    state: present

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  notify: Reboot the servers if SELinux is changed