---
# Common role
- name: Mc package
  package:
    name: mc
    state: present

- name: Nano package
  package:
    name: nano
    state: present

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  notify: Reboot the servers if SELinux is changed