---
- name: Monitoring package
  package:
    name:  "{{monitoring_service}}"
    state: "{{ 'present' if monitoring_action == 'install' else 'absent' }}"

- name: Monioring service 
  service:
    name: "{{monitoring_service}}"
    enabled: "{{ true if monitoring_action == 'install' else false }}"
    state: "{{ 'started' if monitoring_action == 'install' else 'stopped' }}"
    
- name: Monitoring exporter package
  package:
    name: "{{monitoring_exporter}}"
    state: "{{ 'present' if monitoring_action == 'install' else 'absent' }}"
  notify: Monitoring needs restart

- name: Monitoring exporter config 
  template:
    src: "{{monitoring_exporter_file_template if monitoring_action == 'install' else '/dev/null' }}"
    dest: "{{monitoring_exporter_file}}"
  notify: Monitoring needs restart

