---
- name: Monitoring service installed
  package:
    name:  "{{monitoring_service}}"
    state: present

- name: Monioring service started
  service:
    name: "{{monitoring_service}}"
    state: started
    enabled: yes

- name: Monitoring exporter installed
  package:
    name: "{{monitoring_exporter}}"
    state: present
  notify: "Moniroing needs restart"

- name: Monitoring exporter config delivered
  template:
    src: "{{monitoring_exporter_file_template}}"
    dest: "{{monitoring_exporter_file}}"
  notify: Monitoring needs restart

